### PR TITLE
Lint cleanup

### PR DESCRIPTION
**Pull request by atomatt**
* Simplify if/else
* Remove unused and unreachable code.
* Improve error message format.
* Fix log message.

### CODE REVIEW

**Comment by emgee** [comment]
@chteufleur would appreciate a quite review if you have time.

**Comment by chteufleur** [comment]
I will do that in a few days.

**Review by chteufleur — COMMENTED** [review]
Don't forget to use "\n" at the end of the log message.

**Comment by chteufleur** [comment]
I saw typos in comments.
 * https://github.com/emgee/go-xmpp/blob/fix-names/src/xmpp/stream.go#L33
   * s/Steam/Stream
 * https://github.com/emgee/go-xmpp/blob/fix-names/src/xmpp/xmpp.go#L79
   * s/Uniquly/Uniquely
   * s/fiter/filter

Looks good to me.

**Comment by emgee** [comment]
Thanks! I fixed the typos - good catch - but a newline is always appended to log messages anyway so it's not really needed.

**Comment by chteufleur** [comment]
Ho, you right. I mixed with "fmt"...

**Pull request merged**
